export const ConfigKey = {
  IS_WITHDRAW: "IS_WITHDRAW",
  PERCENT_WITHDRAW: "PERCENT_WITHDRAW",
  WALLET_ADDRESS_ENDPOINT: "WALLET_ADDRESS_ENDPOINT",
  WALLET_ADDRESS_ENDPOINT_NFT: "WALLET_ADDRESS_ENDPOINT_NFT",
  VALUE_NANOTONS_TRANSACTION: "VALUE_NANOTONS_TRANSACTION", //Toncoin in nanotons
  VALUE_NANOTONS_WIN: "VALUE_NANOTONS_WIN",
  TON_SEND_INVITER: "TON_SEND_INVITER",
  MIN_TON_WITHDRAW: "MIN_TON_WITHDRAW",
  FEE_TON_WITHDRAW: "FEE_TON_WITHDRAW",
  MIN_TON_DEPOSIT: "MIN_TON_DEPOSIT",
};

export const TypeOpen = {
  leaderBoard: 1,
  withdraw: 2,
  battle: 3,
  nftsCard: 5,
  inventory: 6,
};

export const ActionChangePage = {
  PREV: 1,
  NEXT: 2,
};
